### ISSUE TITLE
Ideal Equations of Motions Solver Inoperable

### ISSUE THREAD

**Issue by ahspringer** [ahspringer/FixedWing_NAPS#6]
**Branch: EOM_break_out_branch**

The default equations of motion solver will remain the same ideal EOM solver as the v1.0.1, with a mild change in how it's implemented. However, the user has been given the ability to update the system state with any method they see fit. As a result of this change, a separate ideal EOM solver is being written. Currently, the solver relies on the scipy.integrate.solve_ivp function. In this particular case, a system of 3 differential equations is being solved in the __eom_ode() function, returning v_BN_W_dot, gamma_dot, sigma_dot. I am currently receiving the following error:

```
Traceback (most recent call last):
  File "c:\Users\Alex\Dropbox\UA-MME\2023\Fall\ME-594\Project\FixedWing_NAPS\FixedWing_NAPS.py", line 101, in <module>
    run_FW_UAV_GNC_Test(15)
  File "c:\Users\Alex\Dropbox\UA-MME\2023\Fall\ME-594\Project\FixedWing_NAPS\FixedWing_NAPS.py", line 81, in run_FW_UAV_GNC_Test
    new_state = RBFW(acft_Guidance.Vehicle, acft_Guidance.Thrust[-1], acft_Guidance.Lift[-1], acft_Guidance.alpha_c, acft_Guidance.mu, acft_Guidance.h_c, acft_Guidance.v_BN_W[-1], acft_Guidance.gamma[-1], acft_Guidance.sigma[-1], acft_Guidance.mass[-1], acft_Guidance.airspeed[-1], acft_Guidance.lat[-1], acft_Guidance.lon[-1], acft_Guidance.h[-1], acft_Guidance.time[-1], acft_Guidance.dt)
                
  File "c:\Users\Alex\Dropbox\UA-MME\2023\Fall\ME-594\Project\FixedWing_NAPS\vehicle\ideal_EOM.py", line 94, in ideal_EOM_RBFW
    sol = solve_ivp(__eom_ode, [time, time + dt], y0, args=(thrust_c, lift_c, drag, mass, mu_c), method='RK45')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\anaconda3\envs\mae594_env\Lib\site-packages\scipy\integrate\_ivp\ivp.py", line 568, in solve_ivp
    solver = method(fun, t0, y0, tf, vectorized=vectorized, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\anaconda3\envs\mae594_env\Lib\site-packages\scipy\integrate\_ivp\rk.py", line 94, in __init__
    self.f = self.fun(self.t, self.y)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\anaconda3\envs\mae594_env\Lib\site-packages\scipy\integrate\_ivp\base.py", line 154, in fun
    return self.fun_single(t, y)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\anaconda3\envs\mae594_env\Lib\site-packages\scipy\integrate\_ivp\base.py", line 23, in fun_wrapped
    return np.asarray(fun(t, y), dtype=dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
```

The code as written is:

```
def __eom_ode(t, state, thrust, lift, drag, mass, mu):
    v_BN_W, gamma, sigma = state  # Unpack the state
    v_BN_W_dot = ((thrust - drag) / mass) - utils.const_gravity * np.sin(gamma)
    gamma_dot = (1/v_BN_W) * ((lift * np.cos(mu)/mass) - utils.const_gravity * np.cos(gamma))
    sigma_dot = (1/(v_BN_W * np.cos(gamma))) * (lift * np.sin(mu) / mass)
    return [v_BN_W_dot, gamma_dot, sigma_dot]

y0 = [v_BN_W, gamma, sigma]
sol = solve_ivp(__eom_ode, [time, time + dt], y0, args=(thrust_c, lift_c, drag, mass, mu_c), method='RK45')
v_BN_W = sol.y[0][-1]
gamma = sol.y[1][-1]
sigma = sol.y[2][-1]
```

**Comment by ahspringer** [comment]
_Hey Alexa, who is the biggest idiot contributing to this project?_
_The biggest idiot contributing to this project is you, Alex._

I was feeding it an array of floats for the mu input when it was expecting a single float.
